const {chromium}=require('C:/Users/caohua/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert/strict'),out='rotationV3/artifacts';
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),report={checks:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.stack));page.on('response',r=>{if(r.status()>=400)report.errors.push(r.status()+' '+r.url())});
try{
await page.goto('http://127.0.0.1:5188/rotationV3/?qa=1');await page.waitForFunction(()=>window.__liteQA);await page.evaluate(()=>localStorage.setItem('rotationLiteSuspendedRunV1','V2 untouched sentinel'));await page.screenshot({path:out+'/home.png'});await page.locator('#start').click();await page.waitForFunction(()=>__liteQA.game.phase==='play'&&!__liteQA.busy);await page.evaluate(()=>{__liteQA.naturalFall=false;});assert.equal(await page.locator('#buff-hud').isVisible(),false);await page.screenshot({path:out+'/play.png'});
await page.evaluate(()=>{const g=__liteQA.game;g.checkpointScore=g.goal+25;g.completeCheckpoint();__liteQA.refresh();});await page.waitForSelector('.v3-reward-choice',{timeout:15000});assert.equal(await page.locator('.v3-reward-choice').count(),3);assert.equal(await page.locator('#lite-dice-stage').count(),0);assert.equal(await page.evaluate(()=>__liteQA.game.lite.coins),8);
for(const [width,height] of [[390,844],[320,568],[1440,900]]){await page.setViewportSize({width,height});assert(await page.locator('.v3-reward-choice').evaluateAll(nodes=>nodes.every(n=>n.scrollWidth<=n.clientWidth+1&&n.getBoundingClientRect().right<=innerWidth)));assert(!/Buff|buff|骰子|赌桌|大成功/.test(await page.locator('#overlay').innerText()));await page.screenshot({path:out+'/supply-'+width+'.png'});}
await page.setViewportSize({width:390,height:844});const options=await page.locator('.v3-reward-choice').evaluateAll(ns=>ns.map(n=>n.dataset.tool));await page.locator('#v3-shop-open').click();assert.equal(await page.locator('.lite-shop-buy').count(),8);assert.equal(await page.locator('#lite-shop-categories button').count(),3);await page.screenshot({path:out+'/shop.png'});await page.locator('.lite-shop-buy').first().click();await page.waitForSelector('#lite-shop-detail[open]');await page.locator('#lite-shop-detail-buy').click();assert.equal(await page.evaluate(()=>__liteQA.game.lite.coins),3);await page.locator('#lite-next').click();assert.deepEqual(await page.locator('.v3-reward-choice').evaluateAll(ns=>ns.map(n=>n.dataset.tool)),options);
await page.locator('#lite-refresh-reward').click();assert.equal(await page.evaluate(()=>__liteQA.game.lite.roll.freeRefreshes),0);await page.locator('#lite-refresh-reward').click();assert(await page.locator('.v3-reward-choice').first().isDisabled());await page.reload();await page.waitForFunction(()=>window.__liteQA);await page.locator('#start').click();await page.waitForSelector('.v3-reward-choice');await page.waitForFunction(()=>__liteQA.game.lite.roll.adRefreshes===2);assert.equal(await page.evaluate(()=>__liteQA.game.lite.coins),3);report.checks.push('Clear coins → mixed three choices; no Buff/dice UI. Shop preserves free choices; refresh quota and ad wait survive reload.');
const id=await page.locator('.v3-reward-choice').first().getAttribute('data-tool'),before=await page.evaluate(id=>__liteQA.game.lite.tools[id],id);await page.locator('.v3-reward-choice').first().click();await page.locator('#lite-refresh-reward[data-action=next]').click();await page.waitForFunction(()=>__liteQA.game.stage===1&&__liteQA.game.phase==='play');assert.equal(await page.evaluate(id=>__liteQA.game.lite.tools[id],id),before+1);assert.equal(await page.evaluate(()=>localStorage.getItem('rotationLiteSuspendedRunV1')),'V2 untouched sentinel');await page.reload();await page.waitForFunction(()=>window.__liteQA);await page.locator('#start').click();await page.waitForFunction(()=>__liteQA.game.stage===1&&__liteQA.game.phase==='play');report.checks.push('Claim then explicit Next advances once, inventory carries, V3 resumes independently without touching V2 save.');
await page.evaluate(()=>{__liteQA.naturalFall=false;const g=__liteQA.game;g.board=[];g.checkpointScore=0;g.dropsUsed=g.dropLimit;g.checkDropLimit();__liteQA.refresh();});await page.waitForSelector('#lite-revive-ad:visible');await page.locator('#lite-revive-ad').click();await page.waitForFunction(()=>['play','checkpoint-complete'].includes(__liteQA.game.phase)&&!__liteQA.busy,{},{timeout:15000});assert.equal(await page.evaluate(()=>__liteQA.game.dropsRemaining),10);report.checks.push('Ad revive adds ten drops, fills the outline and settles into play or the next supply screen.');
assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;process.exitCode=1;await page.screenshot({path:out+'/failure.png'});}finally{fs.writeFileSync(out+'/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}})();
